heapsort done
Sewvka/OOP-Java pull request #1
Opened 2021-09-23 16:43 UTC by Sewvka

2021-09-23 17:24 UTC, molo4evan requested changes

2021-09-23 17:24 UTC, molo4evan commented on Java/src/main/java/HeapSort.java
> +package main.java;
Кажется, переезд на gradle перешел не совсем удачно :)
- src/main/java - корень исходников (соответственно и для тестов)
- не складывай код прямо в корень, нужен базовый пакет, в котором будут лежать классы, я упоминал об этом на паре
- хороший тон - делать для тестов такой же базовый пакет, как и для кода

2021-09-23 18:15 UTC, molo4evan requested changes

2021-09-23 18:15 UTC, molo4evan commented on Java/src/main/java/HeapSort.java
> +    static public void sort(int[] arr)
Корректнее делать `public static` (для остальных модификаторов области видимости также актуально)

2021-09-23 18:15 UTC, molo4evan commented on Java/src/main/java/HeapSort.java
> +            int swap = array[i];
Вынеси в метод (вижу 2 применения в классе, дублирование кода - нехорошо)

2021-09-23 18:15 UTC, molo4evan commented on Java/src/test/java/TestExample.java
> +    public void testHeapSort1() {
Самодокументированные названия методов, Карл!

И речь не только о подходе к написанию тестов, в обычном коде методы вида `fun1`, `fun2`, `fun3`... - это тоже неприемлемый нейминг

Название теста должно вкратце отражать его суть. Обычно это что-то вида `testЧтоДелаемExpectЧтоОжидаем` или что-то подобное. Если получаются громоздкие названия методов - можно ипользовать `@DisplayName`, там вообще можно как хочеш расписать

2021-09-23 18:15 UTC, molo4evan commented on Java/src/test/java/TestExample.java
> +        int[] expResult = {1, 2, 3, 4, 5};
Не стоит руками дублировать, можно нарваться на ошибку

Лучше, например, через `Arrays.copyOf` и `Arrays.sort`

2021-09-23 18:15 UTC, molo4evan commented on Java/src/test/java/TestExample.java
> +class HeapSortTest {
А если вместо массива `null` закинем - что будет?

2021-10-01 15:00 UTC, Sewvka commented on Java/src/main/java/HeapSort.java
> +package main.java;
Done

2021-10-01 15:01 UTC, Sewvka commented on Java/src/test/java/TestExample.java
> +    public void testHeapSort1() {
Parameterized tests with names added

2021-10-08 05:32 UTC, molo4evan commented on Java/src/main/java/HeapSort.java
> +package main.java;
Тесты все еще в корневом пакете)

2021-10-08 05:34 UTC, molo4evan commented on Java/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Сразу что-то тормознул. Кажется, ты как-то некорректно нагенерил gitignore, файлов идеи не должно быть в репозитории. Юзай https://gitignore.io

2021-12-10 05:28 UTC, merged